-- 상품 테이블
CREATE TABLE TBL_PRODUCT(
    PNO NUMBER CONSTRAINT PK_PNO PRIMARY KEY,
    PNAME NVARCHAR2(50) NOT NULL,
    PPRICE NUMBER NOT NULL,
    PCODE NVARCHAR2(50),
    PTYPE NUMBER(1) NOT NULL, -- 노트북:1, 모니터:2, 태블릿:3, 음향기기:4, 주변기기:5
    PINFO_MAIN NVARCHAR2(30),
    PINFO1 NVARCHAR2(50),
    PINFO2 NVARCHAR2(50),
    PINFO3 NVARCHAR2(50),
    PIMAGE_THOUMB NVARCHAR2(50),
    PIMAGE_INFO1 NVARCHAR2(50),
    PIMAGE_INFO2 NVARCHAR2(50),
    PREGDATE DATE DEFAULT SYSDATE
);

INSERT INTO TBL_PRODUCT(PNO, PNAME, PPRICE, PCODE, PTYPE, PINFO_MAIN, PINFO1, PINFO2, PINFO3, PIMAGE_THOUMB, PIMAGE_INFO1, PIMAGE_INFO2)
VALUES (SEQ_PNO.NEXTVAL,
        'Galaxy Book4 Pro',
        3140000,
        'NT960QGK-KD72G',
        1,
        '40.6 cm WQXGA + AMOLED 디스플레이',
        '운영체계,Windows 11 Home',
        '프로세서/칩셋, Intel® Core™ Ultra 7 Processor 155H',
        '메모리, 32GB LPDDR5X Memory (On Board 32GB)',
        'galaxybook4pro.png',
        'galaxybook4pro2.jpg',
        'galaxybook4pro3.jpg');
        
CREATE TABLE TBL_PRODUCT_OPTION(
    PNO NUMBER CONSTRAINT FK_PNO REFERENCES TBL_PRODUCT(PNO),
    ONAME NVARCHAR2(10) NOT NULL,
    OPRICE NUMBER(7) NOT NULL,
    OTYPE NUMBER(1) NOT NULL
);