CREATE TABLE TBL_REVIEW(
    RNO NUMBER PRIMARY KEY,
    PNO NUMBER CONSTRAINT FK_REVIEW_PNO REFERENCES TBL_PRODUCT(PNO),
    MID NVARCHAR2(20) NOT NULL CONSTRAINT FK_REVIEW_MID REFERENCES TBL_MEMBER(MID),
    RCONTENT NVARCHAR2(100) NOT NULL,
    RGRADE NUMBER(1) DEFAULT 5,
    RREGDATE DATE DEFAULT SYSDATE);
    
CREATE SEQUENCE SEQ_REVIEW;